---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-kernel-boot
  name: vmi-kernel-boot
spec:
  domain:
    devices: {}
    firmware:
      kernelBoot:
        container:
          image: occ-quay.apps.sno.oset.amd.com/alan/kubepod/alpine-ext-kernel-boot-demo:2.0.1
          initrdPath: /boot/initramfs-virt
          kernelPath: /boot/vmlinuz-virt
        kernelArgs: console=ttyS0
    memory:
      guest: 1Gi
    resources: {}
  terminationGracePeriodSeconds: 0
