---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-multus-ptp
  name: vmi-multus-ptp
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: ptp
      rng: {}
    memory:
      guest: 1024M
    resources: {}
  networks:
  - multus:
      networkName: ptp-conf
    name: ptp
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: occ-quay.apps.sno.oset.amd.com/alan/kubepod/fedora-with-test-tooling-container-disk:2.0.1
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
